name: ADO Fix Flow
on:
  repository_dispatch:
    types: [ado-workitem-resolved]

jobs:
  apply-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Derive branch name
        id: vars
        run: |
          echo "BRANCH=fix/wi-${{ github.event.client_payload.work_item_id }}" >> $GITHUB_OUTPUT

      - name: Create branch & apply placeholder fix
        run: |
          git config --global user.name "ADO Bot"
          git config --global user.email "ado-bot@example.com"
          git checkout -b "${{ steps.vars.outputs.BRANCH }}"
          mkdir -p docs
          echo "<!-- Automated fix for ADO Work Item #${{ github.event.client_payload.work_item_id }} -->" >> docs/fix-log.md
          echo "## Fix Applied for ADO Work Item #${{ github.event.client_payload.work_item_id }}" >> docs/fix-log.md
          echo "" >> docs/fix-log.md
          echo "**Title:** ${{ github.event.client_payload.title }}" >> docs/fix-log.md
          echo "**Changed by:** ${{ github.event.client_payload.changed_by }}" >> docs/fix-log.md
          echo "**Date:** $(date)" >> docs/fix-log.md
          echo "" >> docs/fix-log.md
          git add -A
          git commit -m "Automated fix for ADO WI #${{ github.event.client_payload.work_item_id }}: ${{ github.event.client_payload.title }}"
          git push origin "${{ steps.vars.outputs.BRANCH }}"

      - name: Create Pull Request
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "title": "🔧 Automated Fix for ADO WI #${{ github.event.client_payload.work_item_id }}",
              "body": "## Automated Fix Pipeline\n\nThis PR was automatically created from Azure DevOps work item resolution.\n\n### Work Item Details\n- **ID:** #${{ github.event.client_payload.work_item_id }}\n- **Title:** ${{ github.event.client_payload.title }}\n- **Changed by:** ${{ github.event.client_payload.changed_by }}\n- **Status:** Resolved\n\n### Changes Made\n- Added fix log entry to `docs/fix-log.md`\n- Applied automated remediation\n\n**🤖 This PR was created automatically by the ADO→GitHub automation loop**",
              "head": "${{ steps.vars.outputs.BRANCH }}",
              "base": "main"
            }' \
            "https://api.github.com/repos/${{ github.repository }}/pulls"
